### ISSUE TITLE
Gulp support

### ISSUE THREAD

**Issue by charlespeters** [sheetify/sheetify#11]
is there a way too put this in a .pipe() in gulp?

my use case is i want a local file to be watched and on file change for my css to be re-bundled.

**Comment by yoshuawuyts** [comment]
I haven't tested it, but https://github.com/hughsk/vinyl-source-stream might work.

**Comment by yoshuawuyts** [comment]
Before #13 is resolved, a way to get it working would be to use [vinyl-source-stream](https://github.com/hughsk/vinyl-source-stream):
```js
const source = require('vinyl-source-stream')
const fromString = require('from2-string')
const gulp = require('gulp')

gulp.task('sheetify', function() {
  sheetify('./index.css').bundle(function (err, css) {
  if (err) throw err
  fromString(css)
    .pipe(source('index.css'))
    .pipe(gulp.dest('./'))
  })
})
```
Let me know if this works for you. Cheers!
