### ISSUE TITLE
getting an error when trying to create a bundle

### ISSUE THREAD

**Issue by jekrb** [sheetify/sheetify#15]
I may be doing something wrong.
`sheetify styles/app.css > bundle.css`

```
/home/jacob/example-css-npm/node_modules/sheetify/node_modules/style-deps/node_modules/css/lib/parse/index.js:69
    throw err;
    ^

Error: missing '{' near line 2:1
    at error (/home/jacob/example-css-npm/node_modules/sheetify/node_modules/style-deps/node_modules/css/lib/parse/index.js:64:15)

```

**Comment by yoshuawuyts** [comment]
That's odd, the commands look fine to me. I just ran and tested `sheetify` on the example in the codebase, and it compiles fine. Could you test it on a simple file and see if that works for you? Just to verify it isn't your code that contains an error.

 Also: what version of node / npm / sheetify are you running?

**Comment by jekrb** [comment]
node -v 3.2.0
npm -v 2.13.4
sheetify 2.0.0

running it in a simple example seems to work, I must have overlooked something before. Sorry about that!

**Comment by jekrb** [comment]
ahhhh I wasn't putting the ./ before the file names.  silly mistake.  sorry again!

**Comment by jekrb** [comment]
Also thanks for this awesome module!

**Comment by yoshuawuyts** [comment]
:grin:
