### ISSUE TITLE
consume postcss plugins

### ISSUE THREAD

**Issue by yoshuawuyts** [sheetify/sheetify#16]
postcss has quite the list of plugins available, perhaps it would be wise to leverage that. I'd be mostly interested in loading the `cssnext` pack:
- https://github.com/postcss/postcss#packs

**Comment by yoshuawuyts** [comment]
Supported in `v3`

**Comment by ahdinosaur** [comment]
@yoshuawuyts how does one consume a postcss plugin in `v3`?

i see https://github.com/sheetify/sheetify/blob/master/index.js#L55-L77, but that seems like sheetify-specific transforms, whereas postcss plugins (so far only the prefix plugin) are applied at https://github.com/sheetify/sheetify/blob/master/index.js#L30-L33.

**Comment by yoshuawuyts** [comment]
I believe we're exposing a different interface from PostCSS at the moment. Not sure if this should be overhauled with multiple preprocessors in mind. Thoughts @hughsk?
