### ISSUE TITLE
--watch/-w option

### ISSUE THREAD

**Issue by sethvincent** [sheetify/sheetify#21]
Are there plans to add a watch option?

So far I've been using chokidar-cli to do something like this:

```
chokidar 'css/*.css' -c 'npm run bundle-css'
```

Where the `bundle-css` script is the `sheetify` command.

That works fine for now. But being able to watch changes with `-w` would be neat.

**Comment by yoshuawuyts** [comment]
Good one, adding a watch mode would be grand! Though perhaps this shouldn't be part of core, but rather as an external extension? Main argument for that would be build time: building chokidar takes a reasonable amount of time and perhaps not always needed. I believe @hughsk had ideas on how to integrate it with `watchify`.

**Comment by ahdinosaur** [comment]
we're also not emitting `file` events in our browserify transform, so changes to the style files are not being watched.

**Comment by yoshuawuyts** [comment]
hmm, good point. That would make for a nice addition
