### ISSUE TITLE
template strings for sheetify

### ISSUE THREAD

**Issue by yoshuawuyts** [sheetify/sheetify#31]
I'm quite fond of [hyperx](https://github.com/substack/hyperx), and how they use template strings. Might be cool to support them too in sheetify, e.g.
```js
const vdom = require('virtual-dom')
const hyperx = require('hyperx')
const sf = require('sheetify')
const hx = hyperx(vdom.h)

const prefix = sf`
  h1 {
    text-align: center;
  }
`

const tree = hx`
  <section className=${prefix}>
    <h1>My beautiful, centered title</h1>
  </section>
`

console.log(vdom.create(tree).toString())
```

Does this make sense? Am I mad? I feel like this might be a bit too much / we really need to start thinking of how to consolidate the API as currently there's already too many ways of doing things haha, though this might be very useful.

**Comment by ahdinosaur** [comment]
ooh, cool idea.

> we really need to start thinking of how to consolidate the API as currently there's already too many ways of doing things

i agree. :)

**Comment by yoshuawuyts** [comment]
[mdn](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings) reference on how to create tagged template strings:
```js
var a = 5;
var b = 10;

function tag(strings, ...values) {
  console.log(strings[0]); // "Hello "
  console.log(strings[1]); // " world "
  console.log(values[0]);  // 15
  console.log(values[1]);  // 50

  return "Bazinga!";
}

tag`Hello ${ a + b } world ${ a * b }`;
// "Bazinga!"
```
