### ISSUE TITLE
exorcise inline styles from the resulting browserify bundle

### ISSUE THREAD

**Issue by yoshuawuyts** [sheetify/sheetify#34]
From https://github.com/sheetify/sheetify/issues/32

When `browserify -t sheetify` has run, we must include a mechanism to remove the inline styles and concat them to a `bundle.css` file.

This should be able to run whenever `watch` is triggered as described in https://github.com/sheetify/sheetify/issues/21

**Comment by ahdinosaur** [comment]
i did a first attempt with [`bundle-cssify`](https://github.com/sheetify/bundle-cssify) (should probably be renamed to `extract-cssify`) towards this. feedback would be great, not sure the best approach, see also https://github.com/davidguttman/cssify/issues/21#issuecomment-170313035 which follows from https://github.com/davidguttman/cssify/pull/45#issuecomment-167536769.

**Comment by yoshuawuyts** [comment]
Oh yeah, that's looking good! Few questions tho:

What's the reason they're being served to a dir rather than concatenated? If files are namespaced I reckon they're safe to be concatenated, as long as `{global: true}` files are prepended in order first (#35). I reckon this would be useful enough of a feature to include directly into `sheetify`, though pulling in an external module should be fine too?

What do you have in mind?

**Comment by ahdinosaur** [comment]
> What's the reason they're being served to a dir rather than concatenated?

i wasn't sure how to write a browserify transform that concatenated "output from many transforms" to a single file. :wink: you're right that order kinda matters, which the current directory approach fails at.

> I reckon this would be useful enough of a feature to include directly into sheetify,

i'd rather we try and do this as separate modules, so we can share code with similar projects. possibly `sheetify` becomes a grab bag for relevant modules, that's cool.

**Comment by yoshuawuyts** [comment]
> grab bag for relevant modules

:ok_hand:

**Comment by yoshuawuyts** [comment]
Closed by #42
